import { join, dirname, basename } from 'path'
import { existsSync } from 'fs'
import chokidar from 'chokidar'
import { getRomsPath } from '../utils/paths'
import { LibraryService } from './LibraryService'
import { SystemsParser } from '../parsers/SystemsParser'
import { BrowserWindow } from 'electron'

export class RomsWatcherService {
  private watcher: chokidar.FSWatcher | null = null
  private libraryService: LibraryService
  private systemsParser: SystemsParser
  private queuedSystems: Set<string> = new Set()
  private debounceTimeout: NodeJS.Timeout | null = null

  constructor(libraryService: LibraryService) {
    this.libraryService = libraryService
    this.systemsParser = new SystemsParser()
  }

  public start(): void {
    if (this.watcher) return

    const romsPath = getRomsPath()
    if (!existsSync(romsPath)) return

    console.log(`📡 Starting ROMs watcher on: ${romsPath}`)

    this.watcher = chokidar.watch(romsPath, {
      ignored: (filePath: string) => {
        // Ignore hidden files/directories (starting with dot)
        if (/(^|[\/\\])\../.test(filePath)) return true

        const lowerPath = filePath.toLowerCase()
        const filename = basename(lowerPath)

        // Ignore common save/state/config extensions
        if (
          lowerPath.endsWith('.sram') ||
          lowerPath.endsWith('.eeprom') ||
          lowerPath.endsWith('.sav') ||
          lowerPath.endsWith('.srm') ||
          lowerPath.endsWith('.state') ||
          lowerPath.endsWith('.nv') ||
          lowerPath.endsWith('.nvram') ||
          lowerPath.endsWith('.cfg') ||
          lowerPath.endsWith('.keys') ||
          lowerPath.endsWith('.conf') ||
          lowerPath.endsWith('.log') ||
          filename === 'gamelist.xml'
        ) {
          return true
        }

        // Ignore specific save/config files generated by emulator engines
        if (
          filename === 'sram.bin' ||
          filename === 'eeprom.bin' ||
          filename === 'sram' ||
          filename === 'eeprom' ||
          filename === 'buffer.ini' ||
          filename === 'controls.ini'
        ) {
          return true
        }

        // Ignore media folders to avoid triggering on cover art, videos, etc.
        if (
          lowerPath.includes('/media/') ||
          lowerPath.includes('\\media\\') ||
          lowerPath.includes('/images/') ||
          lowerPath.includes('\\images\\') ||
          lowerPath.includes('/videos/') ||
          lowerPath.includes('\\videos\\') ||
          lowerPath.includes('/downloaded_images/') ||
          lowerPath.includes('\\downloaded_images\\')
        ) {
          return true
        }

        return false
      },
      persistent: true,
      ignoreInitial: true,
      depth: 3, // depth is 3 because we watch roms/<system>/<file> or subfolders
      awaitWriteFinish: {
        stabilityThreshold: 2000,
        pollInterval: 100
      }
    })

    const handleChange = (filePath: string) => {
      // Resolve system folder name
      const relativePath = filePath.substring(romsPath.length).replace(/\\/g, '/').replace(/^\//, '')
      const pathParts = relativePath.split('/')
      if (pathParts.length < 2) return // Needs to be inside a system folder

      const systemName = pathParts[0]
      // Queue system sync
      this.queueSystemSync(systemName)
    }

    this.watcher
      .on('add', handleChange)
      .on('change', handleChange)
      .on('unlink', handleChange)
  }

  public stop(): void {
    if (this.watcher) {
      this.watcher.close()
      this.watcher = null
    }
    if (this.debounceTimeout) {
      clearTimeout(this.debounceTimeout)
      this.debounceTimeout = null
    }
  }

  private queueSystemSync(systemName: string): void {
    this.queuedSystems.add(systemName)

    if (this.debounceTimeout) {
      clearTimeout(this.debounceTimeout)
    }

    this.debounceTimeout = setTimeout(() => {
      this.processSyncQueue()
    }, 1000) // Debounce 1 second to handle batch operations
  }

  private processSyncQueue(): void {
    const systems = this.systemsParser.parse()
    const dbService = LibraryService.getDatabase()

    if (!dbService.isOpen()) {
      dbService.open()
    }

    const systemsToProcess = Array.from(this.queuedSystems)
    this.queuedSystems.clear()

    let updated = false

    for (const sysName of systemsToProcess) {
      const system = systems.find(s => s.name.toLowerCase() === sysName.toLowerCase())
      if (system) {
        try {
          console.log(`🔄 Watcher triggering database sync for: ${system.name}`)
          
          // Clear cached system info first
          LibraryService.clearCache()
          
          const scanFn = this.libraryService.scanPhysicalGames.bind(this.libraryService)
          dbService.syncSystem(system, scanFn, false) // sync without logging to console too much
          
          updated = true
        } catch (err) {
          console.error(`Error syncing system ${sysName} via watcher:`, err)
        }
      }
    }

    if (updated) {
      // Notify the frontend to reload the systems/games list
      try {
        const win = BrowserWindow.getAllWindows()[0]
        if (win && !win.isDestroyed()) {
          console.log('Sending systems-updated event to UI...')
          win.webContents.send('systems-updated')
        }
      } catch (err) {
        console.error('Failed to notify UI of ROMs update:', err)
      }
    }
  }
}
